"""empty message

Revision ID: 21a3099a2d80
Revises: 
Create Date: 2021-03-05 19:48:33.767764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a3099a2d80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'person_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('person_type', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
