"""empty message

Revision ID: 3585998139f2
Revises: 
Create Date: 2020-01-27 17:04:54.516247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3585998139f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('sportId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'coach', type_='foreignkey')
    op.create_foreign_key(None, 'coach', 'sport', ['sportId'], ['id'])
    op.drop_column('coach', 'sport_id')
    op.add_column('referee', sa.Column('sportId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'referee', type_='foreignkey')
    op.create_foreign_key(None, 'referee', 'sport', ['sportId'], ['id'])
    op.drop_column('referee', 'sport_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referee', sa.Column('sport_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'referee', type_='foreignkey')
    op.create_foreign_key(None, 'referee', 'sport', ['sport_id'], ['id'])
    op.drop_column('referee', 'sportId')
    op.add_column('coach', sa.Column('sport_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'coach', type_='foreignkey')
    op.create_foreign_key(None, 'coach', 'sport', ['sport_id'], ['id'])
    op.drop_column('coach', 'sportId')
    # ### end Alembic commands ###
