"""empty message

Revision ID: 39a386af0a0a
Revises: 
Create Date: 2021-03-29 21:15:16.297050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a386af0a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coach', type_='foreignkey')
    op.drop_constraint(None, 'coach', type_='foreignkey')
    op.drop_column('coach', 'sport_id')
    op.drop_column('coach', 'team_id')
    op.add_column('coach_sport', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.add_column('coach_team', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'sport_id')
    op.drop_column('player', 'team_id')
    op.add_column('player_parent', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.add_column('player_sport', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.add_column('player_team', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.drop_constraint(None, 'referee', type_='foreignkey')
    op.drop_column('referee', 'sport_id')
    op.add_column('referee_sport', sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referee_sport', 'active')
    op.add_column('referee', sa.Column('sport_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'referee', 'sport', ['sport_id'], ['id'])
    op.drop_column('player_team', 'active')
    op.drop_column('player_sport', 'active')
    op.drop_column('player_parent', 'active')
    op.add_column('player', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.add_column('player', sa.Column('sport_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'player', 'sport', ['sport_id'], ['id'])
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['id'])
    op.drop_column('coach_team', 'active')
    op.drop_column('coach_sport', 'active')
    op.add_column('coach', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.add_column('coach', sa.Column('sport_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'coach', 'sport', ['sport_id'], ['id'])
    op.create_foreign_key(None, 'coach', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
