"""empty message

Revision ID: 8f1f828b853c
Revises: ac630f572ca0
Create Date: 2021-04-07 20:43:51.511921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1f828b853c'
down_revision = 'ac630f572ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('level_type', sa.Enum('UNDEFINED', 'REFEREE', 'COACH', 'PLAYER', name='leveltype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'level_type')
    # ### end Alembic commands ###
