"""empty message

Revision ID: a897ccdc59e1
Revises: 8f1f828b853c
Create Date: 2021-04-07 21:01:54.619783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a897ccdc59e1'
down_revision = '8f1f828b853c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('level', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
