name: build_and_package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8,3.9]

    env:
      SQLALCHEMY_URI: ${{ secrets.SQLALCHEMY_URI }}
      SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_URI }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }} 
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Migrations
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        flask db upgrade

    - name: Test with pytest
      run: |
        pip install -r tests/requirements.txt
        coverage run -m pytest --junitxml=coverage-reports/coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
